const products = [
  {id:1,name:'Linen relaxed shirt',brand:'MARGARET HOWELL',price:790,type:'shirt',condition:'สภาพดีมาก',tag:'VERIFIED',image:'https://images.unsplash.com/photo-1605763240000-7e93b172d754?auto=format&fit=crop&w=700&q=85'},
  {id:2,name:'Bias-cut slip dress',brand:'VINTAGE',price:620,type:'dress',condition:'เหมือนใหม่',tag:'JUST IN',image:'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=700&q=85'},
  {id:3,name:'Wool blend blazer',brand:'COS',price:1250,type:'outerwear',condition:'สภาพดีมาก',tag:'MEASURED',image:'https://images.unsplash.com/photo-1581044777550-4cfa60707c03?auto=format&fit=crop&w=700&q=85'},
  {id:4,name:'Cotton ribbed cardigan',brand:'UNIQLO U',price:480,type:'outerwear',condition:'มีตำหนิเล็กน้อย',tag:'JUST IN',image:'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=700&q=85'},
  {id:5,name:'Boxy poplin shirt',brand:'STUDIO NICHOLSON',price:990,type:'shirt',condition:'เหมือนใหม่',tag:'VERIFIED',image:'https://images.unsplash.com/photo-1564257577124-2d860a887f74?auto=format&fit=crop&w=700&q=85'},
  {id:6,name:'Draped midi dress',brand:'LOCAL LABEL',price:720,type:'dress',condition:'สภาพดีมาก',tag:'MEASURED',image:'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=700&q=85'},
  {id:7,name:'Soft denim overshirt',brand:'LEVI’S',price:850,type:'outerwear',condition:'สภาพดีมาก',tag:'JUST IN',image:'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=700&q=85'},
  {id:8,name:'Silk collar shirt',brand:'VINTAGE',price:690,type:'shirt',condition:'เหมือนใหม่',tag:'VERIFIED',image:'https://images.unsplash.com/photo-1598032895397-b9472444bf93?auto=format&fit=crop&w=700&q=85'}
];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);let activeFilter='all', chosen=products[0];
function render(){const q=$('#searchInput').value.toLowerCase();const items=products.filter(p=>(activeFilter==='all'||p.type===activeFilter)&&(`${p.name} ${p.brand}`.toLowerCase().includes(q)));$('#productGrid').innerHTML=items.map(p=>`<article class="product" data-id="${p.id}"><div class="product-image"><img src="${p.image}" alt="${p.name}"><span class="tag">${p.tag}</span><button class="save" aria-label="บันทึกสินค้า">♡</button></div><div class="product-info"><small>${p.brand}</small><h3>${p.name}</h3><b>฿${p.price.toLocaleString()}</b></div></article>`).join('');}
function show(id){$('#overlay').classList.remove('hidden');$(id).classList.remove('hidden')}function hideAll(){$('#overlay').classList.add('hidden');$$('.panel,.modal').forEach(x=>x.classList.add('hidden'))}function toast(t){const el=$('#toast');el.textContent=t;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),2800)}
render();
$$('.filter').forEach(b=>b.addEventListener('click',()=>{if(b.id==='filterMore'){toast('ตัวกรองละเอียดจะเปิดในเวอร์ชันถัดไป');return}$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;render()}));$('#searchInput').addEventListener('input',render);
$('#productGrid').addEventListener('click',e=>{const save=e.target.closest('.save');if(save){save.textContent=save.textContent==='♡'?'♥':'♡';toast(save.textContent==='♥'?'บันทึกสินค้าแล้ว':'นำออกจากรายการบันทึกแล้ว');return}const card=e.target.closest('.product');if(!card)return;chosen=products.find(p=>p.id===+card.dataset.id);$('#detailImage').src=chosen.image;$('#detailBrand').textContent=chosen.brand;$('#detailName').textContent=chosen.name;$('#detailPrice').textContent=`฿${chosen.price.toLocaleString()}`;$('#detailCondition').textContent=chosen.condition;show('#productModal')});
['#openListing','#openListing2'].forEach(s=>$(s).addEventListener('click',()=>show('#listingPanel')));$('#closetButton').addEventListener('click',()=>show('#closetModal'));$$('.close').forEach(b=>b.addEventListener('click',hideAll));$('#overlay').addEventListener('click',hideAll);
$('#aiFill').addEventListener('click',()=>{$('#titleField').value='Linen relaxed shirt, ivory';$('#brandField').value='ไม่ระบุ';$('#conditionField').value='สภาพดีมาก';$('#priceAdvice').innerHTML='<span>✦</span><div><b>คำแนะนำราคา ฿680–฿820</b><p>สภาพดี · ลินิน · เทียบจาก 6 รายการที่มีอยู่</p></div>';toast('AI ร่างข้อมูลให้แล้ว — กรุณาตรวจทานก่อนเผยแพร่')});$('#reviewListing').addEventListener('click',()=>toast('ยังมีข้อมูลขนาดที่วัดจริงไม่ครบ — โปรดกรอกก่อนตรวจทาน'));
$('#favoriteButton').addEventListener('click',e=>{e.currentTarget.textContent=e.currentTarget.textContent==='♡'?'♥':'♡';toast('บันทึกใน My Closet แล้ว')});$('#offerButton').addEventListener('click',()=>{ $('#productModal').classList.add('hidden');show('#offerModal')});$('#sendOffer').addEventListener('click',()=>{hideAll();toast(`ส่งข้อเสนอ ฿${$('#offerInput').value} แล้ว · รอผู้ขายตอบภายใน 24 ชม.`)});$('#buyButton').addEventListener('click',()=>{hideAll();toast('สร้างคำสั่งซื้อจำลองแล้ว · รอชำระเงิน')});
$('#tryonButton').addEventListener('click',()=>{$('#productModal').classList.add('hidden');show('#tryonModal')});$$('.body').forEach(b=>b.addEventListener('click',()=>{$$('.body').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('.measure-label').textContent=b.dataset.body==='petite'?'อก 84 cm':b.dataset.body==='regular'?'อก 90 cm':'อก 96 cm'}));$('#backDetail').addEventListener('click',()=>{$('#tryonModal').classList.add('hidden');show('#productModal')});$('#tryonBuy').addEventListener('click',()=>{hideAll();toast('สร้างคำสั่งซื้อจำลองแล้ว · รอชำระเงิน')});$('#savedSearch').addEventListener('click',()=>toast('บันทึกการค้นหาแล้ว · จะแจ้งเมื่อมีสินค้าที่ตรงกัน'));$('#noticeButton').addEventListener('click',()=>toast('มี 1 ข้อเสนอราคา และพัสดุ 1 รายการกำลังจัดส่ง'));
