import {createRepository} from './repository.js';
import {filterListings,parseSearch,suggestOutfits} from './rules.js';
import {h,money,photoUrl,cover,labels} from './dom.js';
import {openAccounts,openListing,openCloset,openCart,openOffers,openOrders,openNotifications,openReport} from './panels.js';

const repo=await createRepository();let state=await repo.read();let modalRenderer=null;let toastTimer;let chosenPhoto=0;let zoom=1;let panX=0;let panY=0;
const $=id=>document.getElementById(id);
const now=()=>Date.now()+(state.settings.clockOffsetDays||0)*86400000;
const currentUser=()=>state.profiles.find(p=>p.id===state.settings.currentUserId);
const visiblePhoto=l=>l.photos?.[chosenPhoto]||cover(l);
function toast(text){const el=$('toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2800)}
async function run(action,payload={}){const result=await repo.dispatch(action,payload);state=await repo.read();render();if(modalRenderer&&$('modal').open){const body=$('modalBody');body.replaceChildren(modalRenderer())}return result}
function task(fn){Promise.resolve().then(fn).catch(error=>toast(error?.message||'ไม่สามารถทำรายการได้'))}
function close(){modalRenderer=null;$('modal').close()}
function modal(title,renderFn,{wide=false}={}){modalRenderer=renderFn;$('modalTitle').textContent=title;$('modal').classList.toggle('wide',wide);$('modalBody').replaceChildren(renderFn());if(!$('modal').open)$('modal').showModal()}
const ctx={get state(){return state},run,modal,close,toast,task,openProduct,goShop:()=>{close();location.hash='shop'}};

function filters(){return{q:$('searchInput').value,type:$('typeFilter').value,size:$('sizeFilter').value,color:$('colorFilter').value,brand:$('brandFilter').value,minPrice:$('minPriceFilter').value,maxPrice:$('maxPriceFilter').value,condition:$('conditionFilter').value,sort:$('sortFilter').value}}
function renderCard(l){const user=currentUser();const fav=state.favorites?.[user?.id]?.includes(l.id);return h('article',{class:'product-card'},
  h('div',{class:'product-photo',onclick:()=>openProduct(l.id),tabIndex:0,onkeydown:e=>{if(e.key==='Enter')openProduct(l.id)}},h('img',{src:photoUrl(cover(l)),alt:l.title}),h('span',{class:'badge'},labels.condition[l.condition]),h('div',{class:'product-actions'},
    h('button',{title:'ลองจัดชุด',onclick:e=>{e.stopPropagation();task(()=>addTryOn(l.id))}},'＋'),
    h('button',{title:'บันทึก',onclick:e=>{e.stopPropagation();task(()=>run('favorite.toggle',{id:l.id}))}},fav?'♥':'♡'))),
  h('div',{class:'product-info'},h('small',{},l.brand||'ไม่ระบุแบรนด์',' · ',l.size),h('h3',{},l.title),h('span',{class:'price'},money(l.price)),l.refreshedAt?h('span',{class:'updated'},' · อัปเดตแล้ว'):''));
}
function render(){const user=currentUser();$('accountBtn').textContent=user?user.name:'เข้าสู่ระบบเดโม';$('cartCount').textContent=state.carts?.[user?.id]?.length||0;$('clockDays').textContent=state.settings.clockOffsetDays||0;const unread=state.notifications.filter(n=>n.userId===user?.id&&!n.read).length;$('noticeCount').textContent=unread?String(unread):'';
  const list=filterListings(state.listings,filters());$('productGrid').replaceChildren(...list.map(renderCard));$('emptyState').classList.toggle('hidden',!!list.length);renderOutfit()}
function profileOutfit(){const id=state.settings.currentUserId;return state.outfits?.[id]||{items:{},body:{chest:90,waist:72,hip:96,height:165},adjustments:{}}}
function renderOutfit(){const outfit=profileOutfit(),items=outfit.items||{},adjustments=outfit.adjustments||{};$('garmentLayers').replaceChildren(...['bottom','top','dress','outerwear'].map(type=>{const l=state.listings.find(x=>x.id===items[type]),a=adjustments[type]||{};return l?.tryOn?.src?h('img',{class:`garment-layer ${type}`,src:photoUrl(l.tryOn),alt:'',style:`--garment-scale:${a.scale||1};--garment-y:${a.y||0}px`}):null}).filter(Boolean));$('outfitSlots').replaceChildren(...['top','bottom','outerwear','dress'].map(type=>{const l=state.listings.find(x=>x.id===items[type]);return h('div',{class:'slot'},h('small',{},labels.type[type]),h('b',{},l?.title||'ยังไม่ได้เลือก'),l?h('div',{class:'slot-adjust','aria-label':`ปรับภาพ${labels.type[type]}`},h('button',{title:'เลื่อนขึ้น',onclick:()=>task(()=>adjustGarment(type,'y',-4))},'↑'),h('button',{title:'เลื่อนลง',onclick:()=>task(()=>adjustGarment(type,'y',4))},'↓'),h('button',{title:'ย่อ',onclick:()=>task(()=>adjustGarment(type,'scale',-.04))},'−'),h('button',{title:'ขยาย',onclick:()=>task(()=>adjustGarment(type,'scale',.04))},'＋')):null)}));const body=outfit.body||{};for(const k of ['Chest','Waist','Hip','Height']){const el=$(`body${k}`);if(document.activeElement!==el)el.value=body[k.toLowerCase()]||''}$('mannequin').style.setProperty('--body-scale',Math.max(.82,Math.min(1.18,(body.chest||90)/90)))}
async function saveOutfit(outfit){await run('outfit.save',{outfit})}
async function adjustGarment(type,key,delta){const o=structuredClone(profileOutfit());o.adjustments??={};const a=o.adjustments[type]??={scale:1,y:0};a[key]=key==='scale'?Math.max(.76,Math.min(1.24,(a[key]??1)+delta)):Math.max(-28,Math.min(28,(a[key]??0)+delta));await saveOutfit(o)}
async function addTryOn(id){const l=state.listings.find(x=>x.id===id);if(!l?.tryOn){toast('สินค้านี้ไม่มีภาพโปร่งใสสำหรับลอง แต่ยังซื้อและแมตช์ได้');return}const o=structuredClone(profileOutfit());if(l.type==='dress'){delete o.items.top;delete o.items.bottom;o.items.dress=id}else{if(l.type==='top'||l.type==='bottom')delete o.items.dress;o.items[l.type]=id}await saveOutfit(o);location.hash='outfit';toast(`เพิ่ม “${l.title}” ในชุดแล้ว`)}
function measurementText(l){return Object.entries(l.measurements||{}).map(([k,v])=>({chest:'อก',waist:'เอว',hip:'สะโพก',length:'ยาว'}[k]+' '+v+' ซม.')).join(' · ')}
function openProduct(id){chosenPhoto=0;zoom=1;panX=0;panY=0;const build=()=>{const l=state.listings.find(x=>x.id===id);if(!l)return h('p',{},'ไม่พบสินค้านี้');const seller=state.profiles.find(p=>p.id===l.sellerId);const photo=visiblePhoto(l),defect=l.defects?.find(d=>d.photoId===photo?.id)||l.defects?.[0];let drag=null;const updateGallery=el=>{el.style.setProperty('--zoom',zoom);el.style.setProperty('--pan-x',`${panX}px`);el.style.setProperty('--pan-y',`${panY}px`)};return h('div',{class:'detail'},
  h('div',{},h('div',{class:`gallery-main ${photo?.tag==='defect'?'zoomable':''}`,style:`--zoom:${zoom};--pan-x:${panX}px;--pan-y:${panY}px`,tabIndex:photo?.tag==='defect'?0:-1,'aria-label':photo?.tag==='defect'?'ภาพตำหนิ ใช้ปุ่มบวก ลบ หรือลูกศรเพื่อเลื่อนภาพ':'',onwheel:e=>{if(photo?.tag==='defect'){e.preventDefault();zoom=Math.max(1,Math.min(3,zoom+(e.deltaY<0?.2:-.2)));updateGallery(e.currentTarget)}},onkeydown:e=>{if(photo?.tag!=='defect')return;if(e.key==='+'||e.key==='=')zoom=Math.min(3,zoom+.25);else if(e.key==='-')zoom=Math.max(1,zoom-.25);else if(e.key==='ArrowLeft')panX-=10;else if(e.key==='ArrowRight')panX+=10;else if(e.key==='ArrowUp')panY-=10;else if(e.key==='ArrowDown')panY+=10;else return;e.preventDefault();updateGallery(e.currentTarget)},onpointerdown:e=>{if(photo?.tag==='defect'&&zoom>1){drag={x:e.clientX-panX,y:e.clientY-panY};e.currentTarget.setPointerCapture(e.pointerId)}},onpointermove:e=>{if(drag){panX=e.clientX-drag.x;panY=e.clientY-drag.y;updateGallery(e.currentTarget)}},onpointerup:()=>{drag=null}},h('img',{src:photoUrl(photo),alt:`${l.title} ${labels.photo[photo?.tag]||''}`,draggable:false}),photo?.tag==='defect'?h('div',{class:'zoom-controls'},h('button',{onclick:()=>{zoom=Math.min(3,zoom+.25);$('modalBody').replaceChildren(build())},'aria-label':'ขยาย'},'＋'),h('button',{onclick:()=>{zoom=Math.max(1,zoom-.25);$('modalBody').replaceChildren(build())},'aria-label':'ย่อ'},'−'),h('button',{onclick:()=>{zoom=1;panX=0;panY=0;$('modalBody').replaceChildren(build())},'aria-label':'คืนขนาดเดิม'},'1:1')):null),h('div',{class:'thumbs'},...(l.photos||[]).map((p,i)=>h('button',{class:`thumb ${i===chosenPhoto?'active':''}`,onclick:()=>{chosenPhoto=i;zoom=1;panX=0;panY=0;$('modalBody').replaceChildren(build())}},h('img',{src:photoUrl(p),alt:labels.photo[p.tag]}),h('span',{class:'badge'},labels.photo[p.tag]))))),
  h('div',{class:'detail-copy'},h('p',{class:'eyebrow'},l.brand||'ไม่ระบุแบรนด์'),h('h2',{},l.title),h('p',{class:'detail-price'},money(l.price)),h('p',{class:'muted'},'ลงขายโดย ',seller?.name||'ผู้ใช้เดโม'),h('div',{class:'facts'},h('div',{},h('small',{},'สภาพ'),h('b',{},labels.condition[l.condition])),h('div',{},h('small',{},'ไซซ์'),h('b',{},l.size)),h('div',{},h('small',{},'ขนาดวัดจริง'),h('b',{},measurementText(l))),h('div',{},h('small',{},'ทรง'),h('b',{},l.fit))),h('p',{},l.description),defect?h('div',{class:'defect-box'},h('b',{},labels.defect[defect.type],' · ',labels.severity[defect.severity]),h('p',{},defect.description),defect.cleanable?h('small',{},'ผู้ขายระบุว่าอาจซักออกได้'):''):null,h('div',{class:'modal-actions'},h('button',{class:'dark',onclick:()=>task(()=>run('cart.add',{ids:[l.id]}))},'เพิ่มลงตะกร้า'),h('button',{class:'secondary',onclick:()=>task(()=>addTryOn(l.id))},'ลองใส่กับหุ่น'),h('button',{class:'secondary',onclick:()=>openMatches(l.id)},'✦ แมตช์ชุดนี้กับอะไรดี'),h('button',{class:'secondary',onclick:()=>openOfferForm(l)},'เสนอราคา')),h('div',{class:'row'},h('button',{class:'text-btn',onclick:()=>openReport(ctx,l.id)},'รายงานประกาศ/ผู้ขาย'),h('small',{class:'disclaimer'},'ภาพสินค้าเดโมเป็นภาพประกอบ; ตรวจข้อมูลวัดจริงก่อนซื้อ'))))};modal('รายละเอียดสินค้า',build,{wide:true})}
function openOfferForm(l){modal('เสนอราคา',()=>{const input=h('input',{type:'number',min:1,max:l.price-1,value:Math.max(1,l.price-100)});return h('div',{class:'stack'},h('p',{},'ข้อเสนอหมดอายุภายใน 24 ชั่วโมง สินค้ายังไม่ถูกจองจนกว่าจะสร้างคำสั่งซื้อ'),h('label',{class:'field'},'ราคาที่เสนอ',input),h('button',{class:'dark',onclick:()=>task(async()=>{await run('offer.create',{listingId:l.id,amount:Number(input.value)});openOffers(ctx)})},'ยืนยันส่งข้อเสนอ'))})}
function openMatches(anchorId){let budget=$('maxPriceFilter').value||'',rotation=0;const build=()=>{const result=suggestOutfits(anchorId,state.listings,{userId:state.settings.currentUserId,size:$('sizeFilter').value||undefined,budget:budget||undefined});const ordered=result.length?result.map((_,i)=>result[(i+rotation)%result.length]):[];return h('div',{class:'stack'},h('div',{class:'match-budget'},h('label',{class:'field'},'งบรวมไม่เกิน (ไม่รวมค่าส่ง)',h('input',{type:'number',min:1,value:budget,oninput:e=>{budget=e.target.value}})),h('button',{class:'secondary',onclick:()=>{$('modalBody').replaceChildren(build())}},'ใช้เงื่อนไข')),ordered.length?ordered.map(o=>h('article',{class:'match-card'},h('div',{class:'match-items'},...o.ids.map(id=>{const l=state.listings.find(x=>x.id===id);return h('img',{src:photoUrl(cover(l)),alt:l.title,title:l.title})})),h('p',{},o.reason),h('b',{},money(o.total)),h('div',{class:'row'},h('button',{class:'secondary',onclick:()=>{rotation=(rotation+1)%result.length;$('modalBody').replaceChildren(build())}},'เปลี่ยนชิ้น'),h('button',{class:'secondary',onclick:()=>task(async()=>{for(const id of o.ids)await addTryOn(id);close()})},'ลองชุดนี้'),h('button',{class:'dark',onclick:()=>task(()=>run('cart.add',{ids:o.ids}))},'เพิ่มทั้งชุด')))):h('p',{},'ยังไม่มีสินค้าที่เข้าชุดและตรงเงื่อนไข ลองเพิ่มงบ เปลี่ยนไซซ์ หรือล้างตัวกรอง'))};modal('ลุคที่เข้ากันจากสินค้าที่มีขายจริง',build)}

$('modalClose').onclick=close;$('modal').addEventListener('click',e=>{if(e.target===$('modal'))close()});$('accountBtn').onclick=()=>openAccounts(ctx);$('closetBtn').onclick=()=>openCloset(ctx);$('sellBtn').onclick=()=>openListing(ctx);$('cartBtn').onclick=()=>openCart(ctx);$('noticeBtn').onclick=()=>openNotifications(ctx);
for(const id of ['searchInput','typeFilter','sizeFilter','colorFilter','brandFilter','minPriceFilter','maxPriceFilter','conditionFilter','sortFilter'])$(id).addEventListener(['searchInput','minPriceFilter','maxPriceFilter'].includes(id)?'input':'change',render);
$('clearOutfit').onclick=()=>task(()=>saveOutfit({items:{},body:profileOutfit().body,adjustments:{}}));$('addOutfitCart').onclick=()=>task(()=>run('cart.add',{ids:Object.values(profileOutfit().items||{})}));$('matchBtn').onclick=()=>{const id=Object.values(profileOutfit().items||{})[0];id?openMatches(id):toast('เลือกสินค้าอย่างน้อยหนึ่งชิ้นก่อน')};
for(const k of ['Chest','Waist','Hip','Height'])$(`body${k}`).addEventListener('change',()=>task(()=>{const o=structuredClone(profileOutfit());o.body[k.toLowerCase()]=Number($(`body${k}`).value);return saveOutfit(o)}));
$('assistantBtn').onclick=()=>{modal('AI Shopping Assistant',()=>{const input=h('input',{placeholder:'เช่น หาเสื้อสีขาว ไซซ์ M งบไม่เกิน 500 บาท'});return h('div',{class:'stack'},h('p',{},'ผู้ช่วยแบบกฎจะค้นเฉพาะสินค้าที่กำลังขายในเดโม'),input,h('button',{class:'dark',onclick:()=>{const r=parseSearch(input.value),map={q:'searchInput',type:'typeFilter',size:'sizeFilter',color:'colorFilter',brand:'brandFilter',minPrice:'minPriceFilter',maxPrice:'maxPriceFilter',condition:'conditionFilter'};for(const id of Object.values(map))$(id).value='';for(const [key,val] of Object.entries(r.filters||{}))if(map[key]&&val!=null)$(map[key]).value=val;$('assistantResult').replaceChildren(h('b',{},'เข้าใจว่า: '),document.createTextNode(r.understood?.join(' · ')||'ยังไม่พบเงื่อนไขที่รองรับ'));$('assistantResult').classList.remove('hidden');close();render();location.hash='shop'}},'ค้นหาจากสินค้าที่มีจริง'))})};
$('saveSearchBtn').onclick=()=>task(async()=>{await run('search.save',{filters:filters()});toast('บันทึกเงื่อนไขค้นหาใน My Closet แล้ว')});$('clockBtn').onclick=()=>task(async()=>{await run('clock.set',{days:(state.settings.clockOffsetDays||0)+15});await run('maintenance',{});toast('เลื่อนเวลาเดโม 15 วันและประเมินประกาศแล้ว')});
window.addEventListener('closet:changed',()=>task(async()=>{state=await repo.read();render()}));render();task(()=>run('maintenance',{}));
